export const APP_STATUS = {
  INITIAL: 'INITIAL',
  LOADING: 'LOADING',
  LOBBY: 'LOBBY',
  READY: 'READY',
  ERROR: 'ERROR',
  GAME_STARTED: 'GAME_STARTED',
  GAME_OVER: 'GAME_OVER',
  GAME_RESULTS: 'GAME_RESULTS'
}

export type AppStatus = typeof APP_STATUS[keyof typeof APP_STATUS]

export const SECONDS_FOR_QUESTION = 15
export const MAX_QUANTITY_OF_QUESTIONS = 10
